### ISSUE TITLE
Improve job frontend responsiveness

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/simulate#23]
## Goal

To reduce the time it takes to load the job dashboard. This ticket is related to #10

## Acceptance criteria

- [x] Dashboard loads quickly, i.e. quick enough not to annoy the user.
- [x] Finalise rendering of pagination (for example, alan-turing-institute/gateway-frontend@4cfc5809ca7e96de16537e81ca83a48d32f9e8ed currently displays page x of x with no numbers displayed)

## Out of scope

* Auto-refresh of frontend dashboard.
* Middleware pushes status/progress updates to frontend dashboard.

## Implementation notes

* The frontend currently polls the middleware/backend for job status. This is a bottleneck that will be addressed by #10.

**Comment by masonlr** [comment]
@myyong can you please change the `BlueWeb` front-end webpage title to `Gateway` as part of this ticket? Thanks

**Comment by masonlr** [comment]
FYI, issue #67 is related to responsiveness.

**Comment by masonlr** [comment]
@myyong we can close this once the pagination component is tested and fixed.

**Comment by myyong** [comment]
https://github.com/alan-turing-institute/gateway-frontend/commit/c37e79d6104d7df44f5f95c3ed86d5424c00ca3d fixes the pagination for cases.

**Comment by masonlr** [comment]
Front-end support for pagination will be future work: https://github.com/alan-turing-institute/simulate/issues/80
