### ISSUE TITLE
Instructions for deployment

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/simulate#64]
## Goal 
To have README for deploying dockers to run on local.

## Implementation notes
1) Set up instructions for cloud storage in README
2) Set up instructions for compose-up dockers
3) Set up instructions for setting up postgres
4) Set up instructions for adding new case in database

**Comment by masonlr** [comment]
Have linked the top-level "simulate" repository to readthedocs via a webhook. The sphinx documentation will display at:

* https://simulate.readthedocs.io/en/latest/

**Comment by masonlr** [comment]
Need to fix broken readthedocs. Mermaid dependency is breaking the build.

**Comment by masonlr** [comment]
:tada: readthedocs is rendering mermaid

![image](https://user-images.githubusercontent.com/5828176/45769044-57acd300-bc36-11e8-9362-2c12de428685.png)
