### ISSUE TITLE
Output page not accessible

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/simulate#72]
With alan-turing-institute/gateway-frontend@eaef52e0, it is not possible to access the output page, see below:

![image](https://user-images.githubusercontent.com/5828176/41918478-58cf8cde-7954-11e8-92f8-a49e094ddad6.png)

The combination of repositories to reproduce this error is alan-turing-institute/gateway@ac602ff

**Comment by myyong** [comment]
Fix has been pushed and merged here: e913c5c
