### ISSUE TITLE
Job thumbnails are not visible

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/simulate#78]
## Goal 

![image](https://user-images.githubusercontent.com/5828176/42091754-6eb9dd1e-7b9e-11e8-8bc7-401b82d9df13.png)

## Acceptance criteria

- [x] job thumbnails are visible

**Comment by myyong** [comment]
Pull request for bug fix here: https://github.com/alan-turing-institute/gateway-frontend/commit/c37e79d6104d7df44f5f95c3ed86d5424c00ca3d
