### ISSUE TITLE
Login page still shows "Blue Web"

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/simulate#79]
## Description 

Need to update login page.

## Acceptance criteria

- [x] Login page says "Simulate"

**Comment by myyong** [comment]
Fix in https://github.com/alan-turing-institute/gateway-frontend/pull/119/commits/f48cd042f3c89c3b5d5fc07b3f58d9e84c8be0f2, put in for pull request here: https://github.com/alan-turing-institute/gateway-frontend/pull/119
