### ISSUE TITLE
Support persistent storage to Azure from cluster

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/simulate#8]
## Goal

Currently we only support a zip file for output download. This needs to be extended to support multiple files so that, for example, output csv files can be streamed to the browser.

Output files specified by job need to be transferred to persistent Azure cloud storage. Issue is that any content that needs to be visible through the front end must have a corresponding resource URI. 

## Acceptance criteria
- [x] Each job is allocated a temporary SAS access token (to allow write access to Azure storage account)
- [ ] ~~Only transfer files that are listed as `outputs` in the job JSON (support wildcards)~~ (moved to https://github.com/alan-turing-institute/simulate/issues/81)

## Out of scope
- Support for storage on local web server (case where organisational data cannot leave internal network)
- User/team level permissions when accessing Azure storage account resources
- `PROGRESS` script functionality does not need to be supported

## Implementation notes
- Simulator-side sync to be handled by, https://rclone.org
- See alan-turing-institute/science-gateway-middleware#26
- One account per organisation
- One container per simulator
- Blob names are prefixed by `job_id`

**Comment by masonlr** [comment]
`rclone` can be configured using a set of key value pairs

```
rclone config create azure azureblob account sgmiddleware key <SECRET-KEY>
```

creates 

```
[azure]
config_automatic = yes
account = sgmiddleware
key = SECRET-KEY
```

**Comment by masonlr** [comment]
The job manager needs to know how to fetch a SECRET-KEY so that it can run its own `rclone` configuration script. 

Open question:

- [ ] What happens if two instances of `rclone` are needed simultaneously. Does the the `rclone.conf` file affect all instances of `rclone`?

**Comment by masonlr** [comment]
The middleware needs to create a shared access signature (SAS) via the python azure module. The SAS will need to be relayed onwards the backend simulator.

References:
- https://docs.microsoft.com/en-us/python/api/azure.storage.common.sharedaccesssignature.sharedaccesssignature?view=azure-python

**Comment by masonlr** [comment]
v1.37 - 2017-07-22 of `rclone` change logs mention:

* allow auth_url and token_url to be set in the config file

**Comment by masonlr** [comment]
Try a new Azure specific option:

* will look at https://pypi.python.org/pypi/blobxfer/0.9.9.11

**Comment by myyong** [comment]
Relevant code is currently located in https://github.com/alan-turing-institute/science-gateway-middleware/tree/54-openfoam.

We will transfer this code to the new middleware app, once created.

**Comment by masonlr** [comment]
Remaining tasks from this issue are moved to https://github.com/alan-turing-institute/simulate/issues/81
